[package]
name = "ckmeans_py"
version = "1.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_ckmeans"
crate-type = ["cdylib"]

[dependencies]
ckmeans = "2.2"
ndarray = "0.17.2"
numpy = "0.29.0"
pyo3 = { version = "0.29.3", features = ["abi3", "abi3-py311"] }

[profile.release]
lto = true
codegen-units = 1
